# Generated by Django 5.0.2 on 2024-02-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(max_length=32, primary_key=True, serialize=False)),
                ('sno', models.CharField(max_length=32)),
                ('spassword', models.CharField(max_length=32)),
                ('sname', models.CharField(max_length=32)),
                ('sgrade', models.CharField(max_length=32)),
                ('sbirthday', models.CharField(max_length=32)),
            ],
        ),
    ]
