# Generated by Django 5.0.2 on 2024-02-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(max_length=32, primary_key=True, serialize=False)),
                ('tno', models.CharField(max_length=32)),
                ('tpassword', models.CharField(max_length=32)),
                ('tname', models.CharField(max_length=32)),
                ('tcollege', models.CharField(max_length=32)),
                ('tbirthday', models.CharField(max_length=32)),
            ],
        ),
    ]
