# Generated by Django 5.0.2 on 2024-02-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1024)),
                ('content', models.CharField(max_length=2048)),
                ('exectime', models.CharField(max_length=32)),
                ('studentid', models.IntegerField(max_length=11)),
            ],
        ),
    ]
